# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dea8c282b0f4bc6683a4e0d7bc2f131f205185a71f7ad0e10bf3cabc6c331d9bd3abf043904c05142129899c28c02325eef71fae178a02fb8dc6a9351028bf8

test:
  secret_key_base: 5705261c225213e5780ef67ba78c09739a659dbd17b13a614cdbda76bc89bf4239443245b44c09804ba8fb7c1323046d6719514a2db5c69a581d838fbde6cbff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
